/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostHostKeyRouteImport } from './routes/host/$hostKey'
import { Route as HostHostKeyIndexRouteImport } from './routes/host/$hostKey.index'
import { Route as HostHostKeySsrRouteImport } from './routes/host/$hostKey.ssr'
import { Route as HostHostKeyCsrRouteImport } from './routes/host/$hostKey.csr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostHostKeyRoute = HostHostKeyRouteImport.update({
  id: '/host/$hostKey',
  path: '/host/$hostKey',
  getParentRoute: () => rootRouteImport,
} as any)
const HostHostKeyIndexRoute = HostHostKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostHostKeyRoute,
} as any)
const HostHostKeySsrRoute = HostHostKeySsrRouteImport.update({
  id: '/ssr',
  path: '/ssr',
  getParentRoute: () => HostHostKeyRoute,
} as any)
const HostHostKeyCsrRoute = HostHostKeyCsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => HostHostKeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host/$hostKey': typeof HostHostKeyRouteWithChildren
  '/host/$hostKey/csr': typeof HostHostKeyCsrRoute
  '/host/$hostKey/ssr': typeof HostHostKeySsrRoute
  '/host/$hostKey/': typeof HostHostKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host/$hostKey/csr': typeof HostHostKeyCsrRoute
  '/host/$hostKey/ssr': typeof HostHostKeySsrRoute
  '/host/$hostKey': typeof HostHostKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host/$hostKey': typeof HostHostKeyRouteWithChildren
  '/host/$hostKey/csr': typeof HostHostKeyCsrRoute
  '/host/$hostKey/ssr': typeof HostHostKeySsrRoute
  '/host/$hostKey/': typeof HostHostKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host/$hostKey'
    | '/host/$hostKey/csr'
    | '/host/$hostKey/ssr'
    | '/host/$hostKey/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/host/$hostKey/csr' | '/host/$hostKey/ssr' | '/host/$hostKey'
  id:
    | '__root__'
    | '/'
    | '/host/$hostKey'
    | '/host/$hostKey/csr'
    | '/host/$hostKey/ssr'
    | '/host/$hostKey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostHostKeyRoute: typeof HostHostKeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostKey': {
      id: '/host/$hostKey'
      path: '/host/$hostKey'
      fullPath: '/host/$hostKey'
      preLoaderRoute: typeof HostHostKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostKey/': {
      id: '/host/$hostKey/'
      path: '/'
      fullPath: '/host/$hostKey/'
      preLoaderRoute: typeof HostHostKeyIndexRouteImport
      parentRoute: typeof HostHostKeyRoute
    }
    '/host/$hostKey/ssr': {
      id: '/host/$hostKey/ssr'
      path: '/ssr'
      fullPath: '/host/$hostKey/ssr'
      preLoaderRoute: typeof HostHostKeySsrRouteImport
      parentRoute: typeof HostHostKeyRoute
    }
    '/host/$hostKey/csr': {
      id: '/host/$hostKey/csr'
      path: '/csr'
      fullPath: '/host/$hostKey/csr'
      preLoaderRoute: typeof HostHostKeyCsrRouteImport
      parentRoute: typeof HostHostKeyRoute
    }
  }
}

interface HostHostKeyRouteChildren {
  HostHostKeyCsrRoute: typeof HostHostKeyCsrRoute
  HostHostKeySsrRoute: typeof HostHostKeySsrRoute
  HostHostKeyIndexRoute: typeof HostHostKeyIndexRoute
}

const HostHostKeyRouteChildren: HostHostKeyRouteChildren = {
  HostHostKeyCsrRoute: HostHostKeyCsrRoute,
  HostHostKeySsrRoute: HostHostKeySsrRoute,
  HostHostKeyIndexRoute: HostHostKeyIndexRoute,
}

const HostHostKeyRouteWithChildren = HostHostKeyRoute._addFileChildren(
  HostHostKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostHostKeyRoute: HostHostKeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
